CONFIG_KERNEL_VERMAGIC :=

# config for cudy_m3000-v2-yt8821

CONFIG_LINE_ADD := \
	CONFIG_BUILDBOT=n \
	CONFIG_IB_STANDALONE=y \
	CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_cudy_m3000-v2-yt8821=y \
	CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_cudy_ap3000-v1=y \
	\

CONFIG_SED_LINE_DELETE := \
	CONFIG_KERNEL_VERMAGIC \
	CONFIG_TARGET_DEVICE_ \
	CONFIG_BUILDBOT=y \
	CONFIG_IB_STANDALONE=n \
	\
