# thin asu imagebuilder: the official image plus baked-in third-party
# repositories. asu clients (owut, LuCI) cannot pass repositories in build
# requests and asu leaves the image's repositories.conf alone when the
# request has none — same reasoning as imgbuilder.Dockerfile, but without
# a src build: officially supported devices only need the extra repos.
ARG IB_BASE_IMAGE
FROM $IB_BASE_IMAGE

# generated by Img/ReposExtra/File, empty when the config has no
# repositories-extra.conf
ARG IB_REPOS_EXTRA_FILE

USER buildbot
WORKDIR /builder/

# release images ship the imagebuilder pre-unpacked (repositories.conf
# present); snapshot images unpack it at runtime via setup.sh, where this
# append would be lost — the test makes that fail here, at build time
COPY --chown=buildbot $IB_REPOS_EXTRA_FILE ./repositories-extra.conf
RUN test -f repositories.conf && \
    if [ -s repositories-extra.conf ]; then \
        cat repositories-extra.conf >> repositories.conf && \
        sed -i '/check_signature/d' repositories.conf; \
    fi && \
    rm -f repositories-extra.conf
