FROM varch/openwrt-srcbuilder:latest

ARG SRC_ARTIFACTS_DIR
ARG SRC_IMG_BUILDER_FILE
# generated by Img/Builder/Docker/Build, empty when the version has no
# repositories-extra.conf
ARG IB_REPOS_EXTRA_FILE

USER buildbot
WORKDIR /builder/

COPY $SRC_ARTIFACTS_DIR/$SRC_IMG_BUILDER_FILE .
# setup.sh no-op: asu runs it for snapshot builds to download the imagebuilder,
# but here it is already unpacked
RUN tar xf "$SRC_IMG_BUILDER_FILE" --strip=1 --no-same-owner -C . && \
    rm -vrf "$SRC_IMG_BUILDER_FILE" && \
    { [ -f setup.sh ] || printf '#!/bin/sh\nexit 0\n' > setup.sh; }

# bake third-party repositories in: asu clients (owut, LuCI) cannot pass
# repositories in build requests, and asu leaves the image's
# repositories.conf alone when the request has none
COPY --chown=buildbot $IB_REPOS_EXTRA_FILE ./repositories-extra.conf
RUN if [ -s repositories-extra.conf ]; then \
        cat repositories-extra.conf >> repositories.conf && \
        sed -i '/check_signature/d' repositories.conf; \
    fi && \
    rm -f repositories-extra.conf

ENTRYPOINT [ ]
CMD [ "/bin/bash" ]
