CONFIG_KERNEL_VERMAGIC := 6c0cbfffdf5543d41b1de30e3a9c928d

CONFIG_LINE_ADD := \
	CONFIG_TARGET_DEVICE_ramips_mt7621_DEVICE_asus_rt-n56u-b1=y \
	\

CONFIG_SED_LINE_DELETE := \
	CONFIG_KERNEL_VERMAGIC \
	CONFIG_TARGET_DEVICE_ \
	\
