GENERIC_LINE_ADD := \
    CONFIG_MAKE_TOOLCHAIN=n \
    CONFIG_TARGET_ALL_PROFILES=n \
    CONFIG_BPF_TOOLCHAIN_NONE=y \
    CONFIG_BPF_TOOLCHAIN_BUILD_LLVM=n \
    CONFIG_COLLECT_KERNEL_DEBUG=n \
    CONFIG_HAS_BPF_TOOLCHAIN=n \
    CONFIG_SDK=n \
    CONFIG_SDK_LLVM_BPF=n \
    CONFIG_USE_LLVM_BUILD=n \
    CONFIG_REPRODUCIBLE_DEBUG_INFO=n \
    \

GENERIC_SED_LINE_DELETE := \
    CONFIG_MAKE_TOOLCHAIN=y \
    CONFIG_TARGET_ALL_PROFILES=y \
    CONFIG_COLLECT_KERNEL_DEBUG=y \
    CONFIG_SDK=y \
    CONFIG_SDK_LLVM_BPF=y \
    CONFIG_REPRODUCIBLE_DEBUG_INFO=y \
    \
