CONFIG_KERNEL_VERMAGIC := 9f024ec13e17ddc8e779d11356d0d8a0

CONFIG_LINE_ADD := \
	CONFIG_TARGET_DEVICE_sunxi_cortexa53_DEVICE_xunlong_orangepi-zero3=y \
	\

CONFIG_SED_LINE_DELETE := \
	CONFIG_KERNEL_VERMAGIC \
	CONFIG_TARGET_DEVICE_ \
	\
