# src-built core packages (e.g. patched base-files 1672.1 with the almond
# board.d entry) — outranks the official core feed by version
src/gz local_core http://10.10.10.33:8000/releases/24.10.7/targets/ramips/mt7621/packages

src/gz modemfeed https://openwrt.132lan.ru/packages/24.10/packages/mipsel_24kc/modemfeed

# 24.10.7/targets/ramips/mt7621 (mipsel_24kc)
src/gz grinderz_packages-24_10_mipsel_24kc_packages http://10.99.158.1:80/openwrt/releases/packages-24.10/mipsel_24kc/packages
src/gz grinderz_24_10_7_targets_ramips_mt7621_packages http://10.99.158.1:80/openwrt/releases/24.10.7/targets/ramips/mt7621/packages
src/gz grinderz_24_10_7_targets_ramips_mt7621_kmods_6_6_141-1-f31f6f85a36836e510d64a18a9a5f1bf http://10.99.158.1:80/openwrt/releases/24.10.7/targets/ramips/mt7621/kmods/6.6.141-1-f31f6f85a36836e510d64a18a9a5f1bf
