# src-built core packages (e.g. patched base-files 1672.1 with the almond
# board.d entry) — outranks the official core feed by version
#src/gz local_core http://10.10.10.33:8000/releases/24.10.7/targets/ramips/mt7621/packages

src/gz modemfeed https://openwrt.132lan.ru/packages/24.10/packages/aarch64_cortex-a53/modemfeed

# 24.10.7/targets/mediatek/filogic (aarch64_cortex-a53)
src/gz grinderz_packages-24_10_aarch64_cortex-a53_packages http://10.99.158.1:80/openwrt/releases/packages-24.10/aarch64_cortex-a53/packages
src/gz grinderz_24_10_7_targets_mediatek_filogic_packages http://10.99.158.1:80/openwrt/releases/24.10.7/targets/mediatek/filogic/packages
src/gz grinderz_24_10_7_targets_mediatek_filogic_kmods_6_6_141-1-43cbcde0affaaf16309bb4ab09799e9a http://10.99.158.1:80/openwrt/releases/24.10.7/targets/mediatek/filogic/kmods/6.6.141-1-43cbcde0affaaf16309bb4ab09799e9a
